sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build 
      -t cheshirecode/cheshirecode-next-boilerplate 
      --build-arg NODE_ENV=production 
      --build-arg NODE_IMAGE=lts-alpine 
    .
script:
  - docker run --rm 
      -i cheshirecode/cheshirecode-next-boilerplate 
      du -sh .
deploy:
  - provider: script
    script: 
    - yarn deploy
    on:
      master: true